---
- name: Destroy Proxmox VMs
  hosts: all
  gather_facts: false

  vars:
    vmids: "{{ vmids_list | default([]) }}"

  tasks:
    - name: Destroy VMs
      shell: qm destroy {{ item }} --destroy-unreferenced-disks --purge --skiplock
      with_items: "{{ vmids }}"
      register: command_output

    - name: Display Command Output
      debug:
        var: command_output.results