---
- name: Restore from Timeshift Backup
  hosts: all
  become: yes

  tasks:
    - name: List Timeshift Snapshots
      shell: timeshift --list --snapshot-device /dev/sda1
      register: timeshift_output

    - debug:
        var: timeshift_output.stdout_lines

    - name: Extract Latest Snapshot UUID
      set_fact:
        latest_snapshot: "{{ timeshift_output.stdout_lines[-1].split()[2] }}"

    - debug:
        var: latest_snapshot
    
    # - name: Restore from Timeshift Snapshot
    #   shell: timeshift --restore {{ latest_snapshot }} --snapshot-device /dev/sda1